import { useEffect, useMemo, useState } from "react";
import Icon from "../icons";
import { Avatar, EmptyState, PageHeader, Rating, ServiceCard, Sheet } from "../components";
import { api, dateLabel, send } from "../api";

export function ProfileScreen({ me, listings, orders, deals, onNavigate, onSettings }) {
  const ownListings = listings.filter((item) => Number(item.seller_id) === Number(me.id));
  const ownOrders = orders.filter((item) => Number(item.customer_id) === Number(me.id));
  const completed = deals.filter((item) => item.status === "completed").length;
  return <section className="screen profile-screen"><PageHeader eyebrow="ЛИЧНЫЙ КАБИНЕТ" title="Профиль" action={<button className="icon-button" onClick={onSettings}><Icon name="settings"/></button>}/><section className="profile-card"><Avatar src={me.photo_url} name={me.name} size="xl" verified/><div><small>ПРОФИЛЬ TELEGRAM</small><h2>{me.name || "Пользователь LT"}</h2><p>{me.username ? `@${String(me.username).replace(/^@/, "")}` : "Имя пользователя скрыто"}</p><span><i/> Синхронизирован с Telegram</span></div><button onClick={() => onNavigate("seller", { id: me.id })}>Публичный профиль <Icon name="chevron"/></button></section><section className="profile-stats"><span><b>{ownListings.length}</b><small>услуг</small></span><span><b>{ownOrders.length}</b><small>задач</small></span><span><b>{completed}</b><small>завершено</small></span></section><ProfileGroup title="РАБОТА"><ProfileRow icon="grid" title="Мои публикации" text="Услуги, задачи и статусы модерации" count={ownListings.length + ownOrders.length} onClick={() => onNavigate("orders", { tab: "published" })}/><ProfileRow icon="briefcase" title="Заказы и отклики" text="Активная работа и история" count={deals.filter((item) => !["completed", "cancelled"].includes(item.status)).length} onClick={() => onNavigate("orders")}/><ProfileRow icon="heart" title="Избранное" text="Сохранённые услуги" onClick={() => onNavigate("favorites")}/></ProfileGroup><ProfileGroup title="ПОМОЩЬ"><ProfileRow icon="message" title="Поддержка LT Market" text="Вопросы, жалобы и спорные ситуации" onClick={() => onNavigate("support")}/><ProfileRow icon="shield" title="Как работает площадка" text="Краткий путь от поиска до результата" onClick={() => onNavigate("guide")}/><ProfileRow icon="file" title="Правила и документы" text="Условия, приватность и запрещённые услуги" onClick={() => onNavigate("legal")}/></ProfileGroup>{me.is_admin && <button className="admin-entry" onClick={() => onNavigate("admin")}><i><Icon name="shield"/></i><span><small>ДОСТУП КОМАНДЫ</small><b>Центр управления</b></span><Icon name="arrow"/></button>}<footer className="profile-version">LT Market · ранний доступ</footer></section>;
}

function ProfileGroup({ title, children }) { return <section className="profile-group"><small>{title}</small><div>{children}</div></section>; }
function ProfileRow({ icon, title, text, count, onClick }) { return <button onClick={onClick}><i><Icon name={icon}/></i><span><b>{title}</b><small>{text}</small></span>{count ? <em>{count}</em> : null}<Icon name="chevron" size={18}/></button>; }

export function SellerProfileScreen({ profile, reviews = [], onBack, onListing, onFavorite }) {
  if (!profile) return <section className="screen seller-profile-screen"><PageHeader title="Исполнитель" onBack={onBack}/><div className="detail-skeleton"/></section>;
  return <section className="screen seller-profile-screen"><PageHeader eyebrow="ПРОФИЛЬ ИСПОЛНИТЕЛЯ" title="Исполнитель" onBack={onBack}/><section className="seller-hero"><Avatar src={profile.avatar_url} name={profile.display_name || profile.username} size="xl" verified={Boolean(profile.verified)}/><div><small>{profile.level || "Новый исполнитель"}</small><h1>{profile.display_name || profile.username || "Исполнитель LT"}</h1>{profile.username && <p>@{String(profile.username).replace(/^@/, "")}</p>}<Rating rating={profile.rating} count={profile.reviews_count}/></div></section><section className="seller-metrics"><span><b>{profile.completed_orders || 0}</b><small>заказов</small></span><span><b>{Number(profile.rating || 0).toFixed(1)}</b><small>рейтинг</small></span><span><b>{profile.listings?.length || 0}</b><small>услуг</small></span></section>{profile.bio && <article className="seller-about"><small>ОБ ИСПОЛНИТЕЛЕ</small><p>{profile.bio}</p></article>}{profile.skills?.length > 0 && <div className="seller-skills">{profile.skills.map((skill) => <span key={skill}>{skill}</span>)}</div>}<section className="seller-section"><header><h2>Услуги</h2><span>{profile.listings?.length || 0}</span></header>{profile.listings?.length ? <div className="catalog-grid">{profile.listings.map((item) => <ServiceCard key={item.id} item={{ ...item, seller_name: profile.display_name, seller_username: profile.username, avatar_url: profile.avatar_url, avg_rating: profile.rating, reviews_count: profile.reviews_count, seller_verified: profile.verified }} onOpen={() => onListing(item.id)} onFavorite={onFavorite}/>)}</div> : <p className="muted-panel">У исполнителя пока нет активных услуг.</p>}</section><section className="seller-section seller-reviews"><header><h2>Отзывы</h2><span>{reviews.length}</span></header>{reviews.length ? reviews.map((review) => <article key={review.id}><Avatar name={review.reviewer_name} size="sm"/><div><b>{review.reviewer_name}</b><Rating rating={review.rating} count={1} compact/><p>{review.text}</p><small>{dateLabel(review.created_at)}</small></div></article>) : <p className="muted-panel">Отзывы появятся после завершённых заказов.</p>}</section></section>;
}

export function NotificationsScreen({ items, onBack, onOpen, onReadAll }) {
  useEffect(() => { if (items.some((item) => !item.is_read)) onReadAll(); }, [items, onReadAll]);
  const groups = useMemo(() => items.reduce((result, item) => { const key = dateGroup(item.created_at); (result[key] ||= []).push(item); return result; }, {}), [items]);
  return <section className="screen notifications-screen"><PageHeader eyebrow="ЦЕНТР СОБЫТИЙ" title="Уведомления" onBack={onBack} action={items.length ? <button className="text-action" onClick={onReadAll}>Прочитать все</button> : null}/>{items.length ? Object.entries(groups).map(([group, entries]) => <section className="notification-group" key={group}><small>{group}</small>{entries.map((item) => <button className={!item.is_read ? "unread" : ""} key={item.id} onClick={() => onOpen(item)}><i><Icon name={eventIcon(item.event_type)}/></i><span><b>{item.title}</b><p>{item.body}</p><small>{dateLabel(item.created_at)}</small></span>{!item.is_read && <em/>}<Icon name="chevron" size={17}/></button>)}</section>) : <EmptyState icon="bell" title="Пока тихо" text="Здесь будут отклики, сообщения, результаты, правки и статусы заказов." action="Открыть каталог" onAction={() => onOpen({ route: "catalog" })}/>}</section>;
}
function dateGroup(value) { const date = new Date(value); const now = new Date(); if (date.toDateString() === now.toDateString()) return "СЕГОДНЯ"; const yesterday = new Date(now); yesterday.setDate(now.getDate() - 1); return date.toDateString() === yesterday.toDateString() ? "ВЧЕРА" : "РАНЬШЕ"; }
function eventIcon(type) { return ({ message: "message", delivery: "file", revision: "alert", dispute: "shield", review: "star", deal: "briefcase" })[type] || "bell"; }

export function SettingsSheet({ open, preferences, onClose, onSave }) {
  const [form, setForm] = useState(preferences);
  useEffect(() => setForm(preferences), [preferences, open]);
  if (!form) return null;
  const updateNotification = (key) => setForm({ ...form, notifications: { ...form.notifications, [key]: !form.notifications?.[key] } });
  return <Sheet open={open} title="Настройки" onClose={onClose} className="settings-sheet"><div className="settings-content"><section><small>РЕЖИМ РАБОТЫ</small><div className="role-picker">{[["customer", "Заказываю"], ["executor", "Выполняю"], ["both", "Обе роли"]].map(([id, label]) => <button className={form.role === id ? "active" : ""} key={id} onClick={() => setForm({ ...form, role: id })}>{label}</button>)}</div></section><section><small>ОФОРМЛЕНИЕ</small><div className="theme-picker">{[["system", "Как в Telegram"], ["light", "Светлая"], ["dark", "Тёмная"]].map(([id, label]) => <button className={form.theme === id ? "active" : ""} key={id} onClick={() => setForm({ ...form, theme: id })}><i className={id}/><span>{label}</span></button>)}</div></section><section><small>УВЕДОМЛЕНИЯ</small><label className="toggle-row"><span><b>Сообщения и отклики</b><small>Важные события по работе</small></span><input type="checkbox" checked={form.notifications?.messages !== false} onChange={() => updateNotification("messages")}/></label><label className="toggle-row"><span><b>Статусы заказов</b><small>Сроки, результаты и правки</small></span><input type="checkbox" checked={form.notifications?.orders !== false} onChange={() => updateNotification("orders")}/></label><label className="toggle-row"><span><b>Рекомендации</b><small>Новые услуги и подходящие задачи</small></span><input type="checkbox" checked={form.notifications?.recommendations !== false} onChange={() => updateNotification("recommendations")}/></label></section><button className="primary-button wide" onClick={() => onSave(form)}>Сохранить настройки</button></div></Sheet>;
}

export function GuideScreen({ onBack, onCatalog }) {
  const steps = [["search", "Найдите решение", "Выберите готовую услугу или разместите задачу."], ["message", "Согласуйте условия", "Цена, срок и ожидаемый результат сохранятся в заказе."], ["file", "Получите результат", "Примите работу, запросите правку или обратитесь в поддержку."], ["star", "Оставьте отзыв", "Репутация строится только на завершённых заказах."]];
  return <section className="screen guide-screen"><PageHeader eyebrow="КРАТКИЙ ГИД" title="Как работает LT Market" onBack={onBack}/><section className="guide-hero"><Icon name="shield" size={31}/><div><h2>Вся работа — в одном месте</h2><p>От первого сообщения до результата и отзыва.</p></div></section><div className="guide-steps">{steps.map(([icon, title, text], index) => <article key={title}><span>{String(index + 1).padStart(2, "0")}</span><i><Icon name={icon}/></i><div><b>{title}</b><p>{text}</p></div></article>)}</div><article className="guide-safety"><small>ВАЖНО</small><h3>Площадка работает в раннем доступе</h3><p>LT Market пока не принимает и не хранит оплату за заказы. Не переводите деньги по реквизитам из переписки.</p></article><button className="primary-button wide" onClick={onCatalog}>Перейти в каталог <Icon name="arrow"/></button></section>;
}

export function LegalScreen({ onBack, onSupport }) {
  const sections = [
    ["Правила площадки", "Публикуйте только законные цифровые услуги. Не выдавайте чужие работы за свои и не создавайте фиктивные заказы или отзывы."],
    ["Запрещённые услуги", "Нельзя продавать аккаунты, персональные данные, вредоносный код, накрутку, обход ограничений и материалы, нарушающие права других людей."],
    ["Оплата", "LT Market находится в раннем доступе, не принимает и не хранит оплату за заказы, не ведёт рублёвый баланс и не является банковским эскроу."],
    ["Отзывы и споры", "Отзыв доступен после завершённого заказа. При споре сохраняются согласованные условия, сообщения, файлы и история изменений."],
    ["Конфиденциальность", "Профиль связывается с Telegram ID. Контактные и платёжные данные нельзя публиковать в карточках и открытых сообщениях."],
  ];
  return <section className="screen legal-screen"><PageHeader eyebrow="ДОКУМЕНТЫ" title="Правила LT Market" onBack={onBack}/><section className="legal-lead"><Icon name="shield"/><div><h2>Прозрачные правила раннего доступа</h2><p>Коротко о том, что разрешено и как площадка защищает историю работы.</p></div></section><div className="legal-list">{sections.map(([title, text], index) => <article key={title}><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div><button className="secondary-button wide" onClick={onSupport}>Задать вопрос поддержке</button></section>;
}

export function SupportScreen({ onBack, notify }) {
  const [text, setText] = useState("");
  const [tickets, setTickets] = useState([]);
  const [sending, setSending] = useState(false);
  useEffect(() => { api("/api/tickets/history").then(setTickets).catch(() => {}); }, []);
  const submit = async (event) => { event.preventDefault(); setSending(true); try { await send("/api/tickets/new", "POST", { text }); setText(""); notify("Обращение отправлено"); setTickets(await api("/api/tickets/history")); } catch (error) { notify(error.message, "error"); } finally { setSending(false); } };
  return <section className="screen support-screen"><PageHeader eyebrow="ПОМОЩЬ" title="Поддержка" onBack={onBack}/><section className="support-intro"><i><Icon name="message"/></i><div><h2>Разберёмся вместе</h2><p>Опишите проблему. История заказа и действий уже сохранена в системе.</p></div></section><form onSubmit={submit}><label className="field"><span>Новое обращение</span><textarea minLength={8} required value={text} onChange={(event) => setText(event.target.value)} placeholder="Что произошло и с каким заказом?"/></label><button className="primary-button wide" disabled={sending}>{sending ? "Отправляем…" : "Отправить в поддержку"}</button></form><section className="ticket-list"><header><h2>История</h2><span>{tickets.length}</span></header>{tickets.length ? tickets.map((ticket) => <article key={ticket.id}><i className={ticket.status}><Icon name={ticket.status === "closed" ? "check" : "message"}/></i><div><b>Обращение #{ticket.id}</b><p>{ticket.text}</p><small>{dateLabel(ticket.created_at)} · {ticket.status === "closed" ? "Закрыто" : "В работе"}</small></div></article>) : <p className="muted-panel">Обращений пока нет.</p>}</section></section>;
}
