import { useCallback, useEffect, useRef, useState } from "react";
import Icon from "../icons";
import { Avatar, EmptyState, PageHeader, Sheet } from "../components";
import { DEAL_STATUS } from "../constants";
import { api, dateLabel, money, send } from "../api";

function Status({ value }) {
  const [label, tone] = DEAL_STATUS[value] || [value || "Неизвестно", "muted"];
  return <span className={`status-chip ${tone}`}>{label}</span>;
}

export default function OrdersScreen({ me, deals, orders, onNavigate, onCreate, notify, refresh }) {
  const [tab, setTab] = useState("active");
  const [mine, setMine] = useState([]);
  const [applications, setApplications] = useState([]);
  const [requests, setRequests] = useState([]);
  useEffect(() => {
    Promise.all([api("/api/listings/mine"), api("/api/applications/mine"), api("/api/listing-requests/mine")]).then(([nextMine, nextApplications, nextRequests]) => { setMine(nextMine); setApplications(nextApplications); setRequests(nextRequests); }).catch(() => {});
  }, []);
  const activeDeals = deals.filter((item) => !["completed", "cancelled"].includes(item.status));
  const completed = deals.filter((item) => item.status === "completed");
  const ownOrders = orders.filter((item) => Number(item.customer_id) === Number(me.id));
  return <section className="screen orders-screen"><PageHeader eyebrow="РАБОЧЕЕ ПРОСТРАНСТВО" title="Мои заказы" action={<button className="header-create" onClick={(event) => onCreate("order", event.currentTarget.getBoundingClientRect())}><Icon name="plus" size={18}/> Задача</button>}/><div className="orders-tabs"><button className={tab === "active" ? "active" : ""} onClick={() => setTab("active")}>В работе <i>{activeDeals.length}</i></button><button className={tab === "published" ? "active" : ""} onClick={() => setTab("published")}>Публикации <i>{mine.length + ownOrders.length}</i></button><button className={tab === "responses" ? "active" : ""} onClick={() => setTab("responses")}>Отклики <i>{applications.length + requests.filter((item) => item.status === "new").length}</i></button><button className={tab === "history" ? "active" : ""} onClick={() => setTab("history")}>История</button></div>
    {tab === "active" && (activeDeals.length ? <div className="deal-list">{activeDeals.map((deal) => <DealRow key={deal.id} deal={deal} onOpen={() => onNavigate("deal", { id: deal.id })}/>)}</div> : <EmptyState icon="briefcase" title="Активных заказов нет" text="Выберите услугу в каталоге или разместите задачу для исполнителей." action="Открыть каталог" onAction={() => onNavigate("catalog")}/>) }
    {tab === "published" && <div className="publication-list"><SectionTitle title="Мои услуги" count={mine.length}/>{mine.length ? mine.map((item) => <article key={`listing-${item.id}`}><span className={`publication-status ${item.status}`}>{publicationStatus(item.status)}</span><div><small>{item.category}</small><b>{item.title}</b><span>{money(item.price, "от ")}</span></div><button onClick={() => item.status === "active" ? onNavigate("listing", { id: item.id }) : null}><Icon name="chevron"/></button></article>) : <p className="muted-panel">У вас пока нет услуг.</p>}<SectionTitle title="Мои задачи" count={ownOrders.length}/>{ownOrders.length ? ownOrders.map((item) => <article key={`order-${item.id}`}><span className={`publication-status ${item.status}`}>{publicationStatus(item.status)}</span><div><small>{item.category}</small><b>{item.title}</b><span>{money(item.budget, "до ")}</span></div><button onClick={() => onNavigate("order", { id: item.id })}><Icon name="chevron"/></button></article>) : <p className="muted-panel">Вы ещё не размещали задач.</p>}</div>}
    {tab === "responses" && <div className="responses-list"><SectionTitle title="Мои отклики на задачи" count={applications.length}/>{applications.length ? applications.map((item) => <article key={item.id}><Avatar src={item.customer_avatar_url} name={item.customer_name || item.customer_username}/><div><span className={`response-status ${item.status}`}>{responseStatus(item.status)}</span><b>{item.title}</b><p>{item.comment}</p><small>{money(item.price)} · {item.deadline}</small></div></article>) : <p className="muted-panel">Вы пока не откликались на задачи.</p>}<SectionTitle title="Запросы по моим услугам" count={requests.length}/>{requests.length ? requests.map((item) => <IncomingRequest key={item.id} item={item} notify={notify} onChanged={() => { refresh(); setRequests((current) => current.map((entry) => entry.id === item.id ? { ...entry, status: "processed" } : entry)); }}/>) : <p className="muted-panel">Новых запросов нет.</p>}</div>}
    {tab === "history" && (completed.length ? <div className="deal-list">{completed.map((deal) => <DealRow key={deal.id} deal={deal} onOpen={() => onNavigate("deal", { id: deal.id })}/>)}</div> : <EmptyState title="История пока пустая" text="Завершённые заказы появятся здесь."/>)}
  </section>;
}

function SectionTitle({ title, count }) { return <header className="list-section-title"><h2>{title}</h2><span>{count}</span></header>; }
function publicationStatus(status) { return ({ active: "Опубликовано", pending: "На модерации", moderation: "На модерации", rejected: "Отклонено", discussion: "Исполнитель выбран" })[status] || status; }
function responseStatus(status) { return ({ new: "На рассмотрении", accepted: "Принят", declined: "Не выбран", rejected: "Отклонён", processed: "Обработан" })[status] || status; }
function DealRow({ deal, onOpen }) { const partner = deal.role === "customer" ? deal.seller_name : deal.buyer_name; const avatar = deal.role === "customer" ? deal.seller_avatar_url : deal.buyer_avatar_url; return <button className="deal-row" onClick={onOpen}><Avatar src={avatar} name={partner}/><div><span><small>ЗАКАЗ #{deal.id}</small><Status value={deal.status}/></span><b>{deal.title}</b><p>{deal.role === "customer" ? "Исполнитель" : "Заказчик"}: {partner}</p><footer><strong>{money(deal.amount)}</strong><small>{dateLabel(deal.updated_at)}</small></footer></div><Icon name="chevron"/></button>; }

function IncomingRequest({ item, notify, onChanged }) {
  const decide = async (action) => { try { await send(`/api/listing-requests/${item.id}/decision`, "POST", { action }); notify(action === "accept" ? "Запрос принят, заказ создан" : "Запрос отклонён"); onChanged(); } catch (error) { notify(error.message, "error"); } };
  return <article className="incoming-request"><Avatar src={item.buyer_avatar_url} name={item.buyer_name || item.buyer_username}/><div><span className={`response-status ${item.status}`}>{responseStatus(item.status)}</span><b>{item.title}</b><p>{item.message}</p><small>{item.buyer_name || item.buyer_username || "Заказчик"}</small>{item.status === "new" && <footer><button onClick={() => decide("reject")}>Отклонить</button><button className="primary-button" onClick={() => decide("accept")}>Принять</button></footer>}</div></article>;
}

export function DealWorkspace({ me, deal, onBack, notify, onRefresh }) {
  const [messages, setMessages] = useState([]);
  const [deliveries, setDeliveries] = useState([]);
  const [revisions, setRevisions] = useState([]);
  const [text, setText] = useState("");
  const [action, setAction] = useState(null);
  const [payload, setPayload] = useState({ amount: deal?.amount || "", comment: "", reason: "", file_data: "" });
  const bottomRef = useRef(null);
  const isSeller = Number(deal?.seller_id) === Number(me.id);
  const partnerName = isSeller ? deal?.buyer_name : deal?.seller_name;
  const partnerAvatar = isSeller ? deal?.buyer_avatar_url : deal?.seller_avatar_url;
  const load = useCallback(async () => {
    if (!deal) return;
    const [nextMessages, nextDeliveries, nextRevisions] = await Promise.all([api(`/api/deals/${deal.id}/messages`), api(`/api/deals/${deal.id}/deliveries`), api(`/api/deals/${deal.id}/revisions`)]);
    setMessages(nextMessages); setDeliveries(nextDeliveries); setRevisions(nextRevisions);
  }, [deal]);
  useEffect(() => { load().catch(() => {}); }, [load]);
  useEffect(() => bottomRef.current?.scrollIntoView({ behavior: "smooth" }), [messages.length]);
  if (!deal) return null;
  const run = async (nextAction, extra = {}) => { try { await send(`/api/deals/${deal.id}/action`, "POST", { action: nextAction, ...extra }); notify("Статус заказа обновлён"); setAction(null); await onRefresh(); } catch (error) { notify(error.message, "error"); } };
  const sendMessage = async (event) => { event.preventDefault(); if (!text.trim()) return; try { await send(`/api/deals/${deal.id}/messages`, "POST", { text }); setText(""); await load(); } catch (error) { notify(error.message, "error"); } };
  const submitDelivery = async () => { try { await send(`/api/deals/${deal.id}/deliveries`, "POST", { comment: payload.comment, file_data: payload.file_data }); notify("Результат отправлен заказчику"); setAction(null); await load(); await onRefresh(); } catch (error) { notify(error.message, "error"); } };
  return <section className="screen deal-workspace"><PageHeader eyebrow={`ЗАКАЗ #${deal.id}`} title={deal.title} onBack={onBack} action={<Status value={deal.status}/>}/><section className="deal-summary"><button><Avatar src={partnerAvatar} name={partnerName}/><span><small>{isSeller ? "ЗАКАЗЧИК" : "ИСПОЛНИТЕЛЬ"}</small><b>{partnerName}</b></span></button><div><span><small>Стоимость</small><b>{money(deal.amount)}</b></span><span><small>Роль</small><b>{isSeller ? "Исполнитель" : "Заказчик"}</b></span></div></section><DealTimeline status={deal.status}/>
    <section className="workspace-feed"><header><div><small>РАБОЧАЯ ЛЕНТА</small><h2>Обсуждение и файлы</h2></div><span>{messages.length + deliveries.length}</span></header>{!messages.length && !deliveries.length && <p className="feed-empty">Зафиксируйте детали задачи в чате. Переписка останется в истории заказа.</p>}{[...messages.map((item) => ({ ...item, feedType: "message" })), ...deliveries.map((item) => ({ ...item, feedType: "delivery", sortDate: item.created_at }))].sort((a, b) => new Date(a.created_at || a.sortDate) - new Date(b.created_at || b.sortDate)).map((item) => item.feedType === "delivery" ? <article className="delivery-event" key={`delivery-${item.id}`}><i><Icon name="file"/></i><div><span>ВЕРСИЯ {item.version}</span><b>Результат отправлен</b><p>{item.comment}</p><small>{dateLabel(item.created_at)}</small></div></article> : <article className={`chat-message ${Number(item.sender_id) === Number(me.id) ? "mine" : ""}`} key={`message-${item.id}`}><p>{item.text}</p><small>{dateLabel(item.created_at)}</small></article>)}{revisions.map((item) => <article className="revision-event" key={`revision-${item.id}`}><Icon name="alert"/><div><b>Запрошена правка</b><p>{item.text}</p><small>{item.status === "resolved" ? "Исправлено" : "Ожидает результата"}</small></div></article>)}<div ref={bottomRef}/></section>
    <form className="chat-composer" onSubmit={sendMessage}><input value={text} onChange={(event) => setText(event.target.value)} placeholder="Сообщение по заказу"/><button disabled={!text.trim()} aria-label="Отправить"><Icon name="send"/></button></form><DealActions deal={deal} isSeller={isSeller} setAction={setAction} run={run}/>
    <Sheet open={Boolean(action)} title={actionTitle(action)} onClose={() => setAction(null)}><div className="action-sheet">{action === "price" && <><label className="field"><span>Итоговая стоимость, ₽</span><input type="number" value={payload.amount} onChange={(event) => setPayload({ ...payload, amount: event.target.value })}/></label><label className="field"><span>Что входит в результат</span><textarea value={payload.comment} onChange={(event) => setPayload({ ...payload, comment: event.target.value })}/></label><button className="primary-button wide" onClick={() => run("set_final_price", { amount: Number(payload.amount), terms: { result: payload.comment } })}>Отправить условия</button></>}{action === "delivery" && <><label className="field"><span>Что передаёте</span><textarea value={payload.comment} onChange={(event) => setPayload({ ...payload, comment: event.target.value })} placeholder="Опишите результат и изменения в этой версии"/></label><button className="primary-button wide" onClick={submitDelivery}>Отправить результат</button></>}{["revision", "dispute"].includes(action) && <><label className="field"><span>{action === "revision" ? "Что нужно исправить" : "Причина обращения"}</span><textarea value={payload.reason} onChange={(event) => setPayload({ ...payload, reason: event.target.value })}/></label><button className={`wide ${action === "dispute" ? "danger-button" : "primary-button"}`} onClick={() => run(action === "revision" ? "request_revision" : "open_dispute", { reason: payload.reason })}>{action === "revision" ? "Запросить правку" : "Открыть спор"}</button></>}</div></Sheet>
  </section>;
}

function actionTitle(action) { return ({ price: "Согласовать условия", delivery: "Передать результат", revision: "Запросить правку", dispute: "Обратиться к модератору" })[action] || "Действие"; }
function DealActions({ deal, isSeller, setAction, run }) { return <footer className="deal-actions">{isSeller && ["discussion", "waiting_final_price"].includes(deal.status) && <button className="primary-button" onClick={() => setAction("price")}>Предложить условия</button>}{!isSeller && deal.status === "waiting_buyer_price_confirm" && <button className="primary-button" onClick={() => run("confirm_price")}>Подтвердить условия</button>}{isSeller && deal.status === "terms_confirmed" && <button className="primary-button" onClick={() => run("start_work")}>Начать работу</button>}{isSeller && ["in_work", "in_revision"].includes(deal.status) && <button className="primary-button" onClick={() => setAction("delivery")}>Отправить результат</button>}{!isSeller && deal.status === "waiting_buyer_confirm" && <><button onClick={() => setAction("revision")}>Нужна правка</button><button className="primary-button" onClick={() => run("confirm_done")}>Принять работу</button></>}{!["completed", "cancelled", "dispute_open"].includes(deal.status) && <button className="more-action" onClick={() => setAction("dispute")}><Icon name="more"/></button>}</footer>; }
function DealTimeline({ status }) { const stages = ["discussion", "terms_confirmed", "in_work", "waiting_buyer_confirm", "completed"]; const normalized = status === "waiting_buyer_price_confirm" ? "discussion" : status === "in_revision" ? "in_work" : status; const current = stages.indexOf(normalized); return <section className="deal-timeline">{stages.map((stage, index) => <span className={index <= current ? "active" : ""} key={stage}><i>{index < current ? <Icon name="check" size={12}/> : index + 1}</i><small>{["Условия", "Согласовано", "В работе", "Проверка", "Готово"][index]}</small></span>)}</section>; }
