import { useEffect, useState } from "react";
const cards = [["moderation", "Модерация", "Новые услуги и заказы", "✓"], ["payments", "Оплаты", "Проверка чеков и поступлений", "▣"], ["payouts", "Выплаты", "Заявки исполнителей на вывод", "↗"], ["disputes", "Споры", "Разбор проблемных сделок", "!"]];
export default function AdminWorkspace({ summary = {}, onNavigate, onOpenBot, fetchData, request }) {
  const [queue, setQueue] = useState([]); const [opening, setOpening] = useState(false); const [queueMode, setQueueMode] = useState("moderation"); const [notice, setNotice] = useState("");
  const counts = { moderation: summary.moderation ?? 0, payments: summary.payments ?? 0, payouts: summary.payouts ?? 0, disputes: summary.disputes ?? 0 };
  const openQueue = async (mode) => { try { setQueue(await fetchData(mode === "moderation" ? "/api/admin/moderation" : `/api/admin/queues/${mode}`)); setQueueMode(mode); setOpening(true); } catch { setNotice("Не удалось загрузить рабочую очередь."); } };
  const decide = async (item, action) => { try { await request(`/api/admin/moderation/${item.item_type}/${item.id}`, "POST", { action }); setQueue((current) => current.filter((row) => row.id !== item.id || row.item_type !== item.item_type)); setNotice(action === "approve" ? "Публикация одобрена." : "Публикация отклонена."); } catch (error) { setNotice(error?.message || "Не удалось обработать публикацию."); } };
  return <section className="admin-workspace"><header className="admin-workspace-head"><button onClick={() => onNavigate("profile")}>←</button><div><p>LTEAM CONTROL</p><h1>Админ-панель</h1></div><span>ADMIN</span></header><section className="admin-brief"><div><b>{Object.values(counts).reduce((sum, value) => sum + Number(value || 0), 0)}</b><span>требуют внимания</span></div><p>Управляйте проверками и финансовыми действиями через защищённый интерфейс LTeam.</p></section><section className="admin-queue">{cards.map(([key, title, caption, icon]) => <button key={key} onClick={() => openQueue(key)}><i>{icon}</i><span><b>{title}</b><small>{caption}</small></span><strong>{counts[key]}</strong><em>›</em></button>)}</section><section className="admin-tools"><p>ДОПОЛНИТЕЛЬНО</p><button onClick={() => onOpenBot("admin_panel")}>Открыть полную админ-панель бота <span>→</span></button><small>Доступ ограничен администраторами, подтверждёнными сервером.</small></section>{notice && <button className="admin-notice" onClick={() => setNotice("")}>{notice}</button>}{opening && <ModerationSheet queue={queue} mode={queueMode} onClose={() => setOpening(false)} onDecide={decide} onOpenBot={onOpenBot} />}</section>;
}
function ModerationSheet({ queue, mode, onClose, onDecide, onOpenBot }) { const labels={moderation:["ОЧЕРЕДЬ МОДЕРАЦИИ","Новые публикации"],payments:["ПЛАТЕЖИ","Сделки на проверке"],payouts:["ВЫВОДЫ","Заявки исполнителей"],disputes:["СПОРЫ","Проблемные сделки"]}[mode]||["LTEAM","Очередь"]; return <div className="moderation-backdrop" onMouseDown={onClose}><section className="moderation-sheet" onMouseDown={(event) => event.stopPropagation()}><div className="sheet-handle"/><header><div><p>{labels[0]}</p><h2>{labels[1]}</h2></div><button onClick={onClose}>×</button></header>{!queue.length && <div className="moderation-empty">Очередь пуста.</div>}<div className="moderation-list">{queue.map((item) => <article key={`${mode}-${item.id}`}><span>{mode === "moderation" ? (item.item_type === "listing" ? "УСЛУГА" : "ЗАКАЗ") : mode.toUpperCase()}</span><h3>{item.title}</h3><p>{item.description || item.note || "Требуется проверка администратора."}</p><small>{item.category || "LTeam"} · {Number(item.amount || 0).toLocaleString("ru-RU")} ₽</small><footer>{mode === "moderation" ? <><button onClick={() => onDecide(item, "reject")}>Отклонить</button><button onClick={() => onDecide(item, "approve")}>Одобрить</button></> : <button onClick={() => onOpenBot(mode)}>Открыть управление в боте</button>}</footer></article>)}</div></section></div>; }
