import { useEffect, useMemo, useState } from "react";

const cats = ["Все", "Дизайн", "Разработка", "Тексты", "Монтаж", "Другое"];
const person = (x) => x.seller_name || x.seller_username || "Исполнитель LTeam";

export default function CatalogV3({ items, orders, favorites, onFavorite, onNavigate, request }) {
  const [mode, setMode] = useState("services"), [query, setQuery] = useState(""), [cat, setCat] = useState("Все"), [sort, setSort] = useState("new"), [profile, setProfile] = useState(null);
  const source = mode === "services" ? items : orders;
  const data = useMemo(() => source.filter(x => (cat === "Все" || x.category === cat) && `${x.title} ${x.description||""}`.toLowerCase().includes(query.toLowerCase())).sort((a,b) => sort === "rating" ? (b.avg_rating||0)-(a.avg_rating||0) : sort === "low" ? (a.price??a.budget)-(b.price??b.budget) : sort === "high" ? (b.price??b.budget)-(a.price??a.budget) : b.id-a.id), [source,cat,query,sort]);
  const openProfile = async (id) => { try { setProfile(await fetch(`https://lteam-botminiapp.onrender.com/api/users/${id}/public`, {headers:{"X-Telegram-Init-Data":window.Telegram?.WebApp?.initData||""}}).then(r=>r.json())); } catch {} };
  if (profile?.id) { const rate=Number(profile.rating||0), tone=rate>=5?"high":rate>=3.5?"mid":"low"; return <section className="seller-profile"><header><button onClick={()=>setProfile(null)}>‹</button><b>Профиль исполнителя</b></header><div className="seller-profile-card"><div className="seller-profile-avatar">{person(profile).slice(0,1).toUpperCase()}</div><h1>{person(profile)}</h1><span>@{profile.username||"lteam_user"}</span><div className={`seller-rating ${tone}`}>★ {rate?rate.toFixed(1):"Нет оценки"} · {profile.reviews_count||0} отзывов</div></div><h2>Услуги исполнителя</h2><div className="seller-list">{profile.listings.map(x=><article key={x.id}><div><p>{x.category}</p><b>{x.title}</b><small>{x.delivery_time||"Срок по договорённости"}</small></div><strong>от {Number(x.price).toLocaleString("ru-RU")} ₽</strong></article>)}</div></section>; }
  return <section className="catalog-v3"><header><button className="cv-brand" onClick={()=>onNavigate("home")}><i>LT</i><span>Маркет</span></button><button onClick={()=>onNavigate("create-order")}>+ Заказ</button></header><div className="cv-title"><p>LTEAM MARKETPLACE</p><h1>{mode==="services"?"Услуги":"Заказы"}</h1></div><div className="cv-tabs"><button className={mode==="services"?"active":""} onClick={()=>setMode("services")}>Предлагаю услугу</button><button className={mode==="orders"?"active":""} onClick={()=>setMode("orders")}>Ищу исполнителя</button></div><label className="cv-search"><i>⌕</i><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Поиск"/></label><div className="cv-filters"><select value={cat} onChange={e=>setCat(e.target.value)}>{cats.map(x=><option key={x}>{x}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value)}><option value="new">Новые</option><option value="rating">По рейтингу</option><option value="low">Дешевле</option><option value="high">Дороже</option></select></div><div className="cv-list">{data.map(x=>mode==="services"?<article className="service-v3" key={x.id}><div className="service-head" onClick={()=>openProfile(x.seller_id)}><div className="service-avatar">{person(x).slice(0,1).toUpperCase()}</div><div><b>{person(x)}</b><small>@{x.seller_username||"lteam_user"}</small></div><span>★ {(x.avg_rating||0).toFixed(1)} · {x.reviews_count||0}</span></div><div className="service-meta"><span>{x.category}</span><span>{x.delivery_time||"По договорённости"}</span></div><h3>{x.title}</h3><footer><b>от {Number(x.price).toLocaleString("ru-RU")} ₽</b><button onClick={()=>onNavigate("create-order")}>Подробнее</button></footer></article>:<article className="order-v3" key={x.id}><div className="order-v3-top"><span>{x.category}</span><b>до {Number(x.budget).toLocaleString("ru-RU")} ₽</b></div><h3>{x.title}</h3><p>{x.description}</p><footer><span>{x.deadline||"Срок обсуждается"}</span><button onClick={()=>onNavigate("orders")}>Откликнуться</button></footer></article>)}</div></section>;
}
