import { useEffect, useState } from "react";

const money = (value) => `${Number(value || 0).toLocaleString("ru-RU")} ₽`;
const status = { active: ["Опубликовано", "ok"], pending: ["На модерации", "wait"], moderation: ["На модерации", "wait"], rejected: ["Отклонено", "bad"], paused: ["Скрыто", "muted"] };

export default function MyListingsWorkspace({ fetchData, request, onNavigate, onOpenDeal }) {
  const [items, setItems] = useState([]);
  const [requests, setRequests] = useState([]);
  const [loading, setLoading] = useState(true);
  const [notice, setNotice] = useState("");
  useEffect(() => { Promise.all([fetchData("/api/listings/mine"), fetchData("/api/listing-requests/mine")]).then(([listingItems, inbox]) => { setItems(listingItems); setRequests(inbox); }).catch(() => { setItems([]); setRequests([]); }).finally(() => setLoading(false)); }, [fetchData]);
  const decide = async (item, action) => { try { const result = await request(`/api/listing-requests/${item.id}/decision`, "POST", { action }); setRequests((current) => current.map((row) => row.id === item.id ? { ...row, status: result.status, deal_id: result.deal_id || 0 } : row)); setNotice(action === "accept" ? "Сделка создана. Можно сразу открыть чат." : "Запрос отклонён, покупатель получил уведомление."); if (action === "accept" && result.deal_id) onOpenDeal?.(result.deal_id); } catch (error) { setNotice(error?.message || "Не удалось обработать запрос."); } };
  const pending = requests.filter((item) => item.status === "new");
  return <section className="my-publications marketplace-shell"><header className="market-topbar"><button className="market-brand" onClick={() => onNavigate("profile")}><i>LT</i><b>Мои услуги</b></button><button className="market-create" onClick={() => onNavigate("create")}>+ Услуга</button></header><main className="publications-content"><div className="market-heading"><p className="market-eyebrow">ЛИЧНАЯ ВИТРИНА</p><h1>Мои публикации</h1><span>Управляйте услугами и запросами покупателей.</span></div>{pending.length > 0 && <section className="listing-requests"><div className="market-section-title"><div><p className="market-eyebrow">НОВЫЕ ЗАПРОСЫ · {pending.length}</p><h2>Хотят обсудить услугу</h2></div></div>{pending.map((item) => <article key={item.id}><div className="listing-request-person"><span>{(item.buyer_name || item.buyer_username || "L").slice(0,1).toUpperCase()}</span><div><b>{item.buyer_name || item.buyer_username || "Покупатель LTeam"}</b><small>@{item.buyer_username || "lteam_user"}</small></div><em>{item.title}</em></div><p>{item.message}</p><footer><button onClick={() => decide(item, "reject")}>Отклонить</button><button onClick={() => decide(item, "accept")}>Принять и открыть сделку</button></footer></article>)}</section>}{loading ? <div className="publications-empty">Загружаем публикации…</div> : !items.length ? <div className="publications-empty"><b>Услуг пока нет</b><span>Создайте первую услугу и покажите её покупателям.</span><button onClick={() => onNavigate("create")}>Разместить услугу</button></div> : <div className="publications-list">{items.map((item) => { const [label, tone] = status[item.status] || [item.status || "Статус", "muted"]; return <article key={item.id}><div className="publication-cover">{item.image_data ? <img src={item.image_data} alt="" /> : "LT"}</div><div><span className={`publication-status ${tone}`}>{label}</span><h3>{item.title}</h3><p>{item.category} · {money(item.price)}</p><small>{item.description || "Без описания"}</small></div><button onClick={() => onNavigate("catalog")}>Открыть ›</button></article>; })}</div>}</main>{notice && <button className="market-notice" onClick={() => setNotice("")}>{notice}<span>×</span></button>}<nav className="market-dock"><button onClick={() => onNavigate("home")}>⌂<span>Главная</span></button><button onClick={() => onNavigate("catalog")}>▦<span>Маркет</span></button><button onClick={() => onNavigate("orders")}>▤<span>Мои заказы</span></button><button className="active" onClick={() => onNavigate("profile")}>♙<span>Профиль</span></button></nav></section>;
}
